@code=
@refresh_token=
@access_token=

@path=http://localhost:8000
@realm=web
@client_id=test
@redirect_uri=http://localhost:4200

POST {{path}}/realms/{{realm}}/protocol/openid-connect/token 
Content-Type: application/x-www-form-urlencoded

code={{code}}&grant_type=authorization_code&client_id={{client_id}}&redirect_uri={{redirect_uri}}&client_secret=c_id

###

POST {{path}}/realms/{{realm}}/protocol/openid-connect/token 
Content-Type: application/x-www-form-urlencoded

refresh_token={{refresh_token}}&grant_type=refresh_token&client_id={{client_id}}&redirect_uri={{redirect_uri}}&client_secret=c_id

###

GET {{path}}/realms/{{realm}}/protocol/openid-connect/auth?client_id={{client_id}}&scope=openid&redirect_uri={{redirect_uri}}&response_type=code&state=123&nonce=456&response_mode=fragment

###

GET {{path}}/realms/{{realm}}/protocol/openid-connect/certs

###

GET {{path}}/realms/{{realm}}/.well-known/openid-configuration